name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: convert input to int
      id: convert_input
      run: echo "::set-output name=number::${{ github.event.inputs.number }}"
    
    - name: checkout code
      uses: actions/checkout@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run the script 
      run: python EvenorOdd.py ${{ steps.convert_input.outputs.number }}
